/**
 * Created by cuppi on 2017/10/24.
 */

// rootModule
export const ROOT = {
  SHOW_LOADING: 'SHOW_LOADING_MUTATION',
  ALERT_QUESTION: 'ALERT_QUESTION_MUTATION'
};

// locationModule
export const LOCATION = {
  UPDATE_LOCATION: 'UPDATE_LOCATION_MUTATION',
  UPDATE_LOCATION_CITY: 'UPDATE_LOCATION_CITY_MUTATION',
  UPDATE_USER_LOCATION_CITY: 'UPDATE_USER_LOCATION_CITY_MUTATION'
};

// loginModule
export const LOGIN = {
  UPDATE_LOGIN: 'UPDATE_LOGIN_MUTATION',
  UPDATE_ACCOUNT: 'UPDATE_ACCOUNT_MUTATION'
};
