// 根级别的 mutation

import * as types from './mutations-type.js'

const mutations = {
  [types.SET_USER](state, USER) {
    state.USER = USER
  },
  [types.SET_AUTH_URL](state, URL) {
    state.AUTH_URL = URL
  },
  [types.SET_LEADER_CONTACT_CASE](state, LEADER_CONTACT_CASE) {
    state.LEADER_CONTACT_CASE = LEADER_CONTACT_CASE
  },
  [types.SET_SELECT_LEADER_CONTACT_CASE](state, SELECT_LEADER_CONTACT_CASE) {
    state.SELECT_LEADER_CONTACT_CASE = SELECT_LEADER_CONTACT_CASE
  },
  [types.SET_COMMON_PERSON_SELECT_CACHE](state, COMMON_PERSON_SELECT_CACHE) {
    state.COMMON_PERSON_SELECT_CACHE = COMMON_PERSON_SELECT_CACHE
  },
  [types.SET_COMMON_LEADER_SELECTED_CACHE](state, COMMON_LEADER_SELECTED_CACHE) {
    state.COMMON_LEADER_SELECTED_CACHE = COMMON_LEADER_SELECTED_CACHE
  },

//相关人
  [types.SET_COMMON_ABOUT_SELECTED_CACHE](state, COMMON_ABOUT_SELECTED_CACHE) {
    state.COMMON_ABOUT_SELECTED_CACHE = COMMON_ABOUT_SELECTED_CACHE
  },
//@人
[types.SET_AT_PERSON_STATE](state,AT_PERSON_STATE){
  state.AT_PERSON_STATE=AT_PERSON_STATE
}  
}

export default mutations
