// mutation 常量

export const SET_USER = 'SET_USER'
export const SET_AUTH_URL = 'SET_AUTH_URL'
export const SET_LEADER_CONTACT_CASE = 'SET_LEADER_CONTACT_CASE'
export const SET_SELECT_LEADER_CONTACT_CASE = 'SET_SELECT_LEADER_CONTACT_CASE'
//列表缓存
export const SET_COMMON_PERSON_SELECT_CACHE = 'SET_COMMON_PERSON_SELECT_CACHE'
//已选择
export const SET_COMMON_LEADER_SELECTED_CACHE = 'SET_COMMON_LEADER_SELECTED_CACHE'
//相关人
export const SET_COMMON_ABOUT_SELECTED_CACHE = 'SET_COMMON_ABOUT_SELECTED_CACHE'

//@人
export const SET_AT_PERSON_STATE='SET_AT_PERSON_STATE'
